# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd2a00847519eedabbbfdb5e99cdd36a81e4b2163a836093adbcdffef0e5d1e79991981f2bf4377cb466f0f594a499aec6e8bc7a53c2f7d7a088f03240b41997

test:
  secret_key_base: a1ae5bfd41e3131e48f74e64d61298e08ca2f27830e2bec0475977ae3b9cbe8773f577ceaea98bafa20a3c154b4236a0ed401c522492cacf028e517c55010129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
